/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ECDSAExtendedLib,
  ECDSAExtendedLibInterface,
} from "../ECDSAExtendedLib";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0xa712c012",
        type: "bytes32",
      },
    ],
    name: "c_0xa712c012",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x6073610024600b82828239805160001a607314601757fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80635178dde5146038575b600080fd5b606160048036036020811015604c57600080fd5b81019080803590602001909291905050506063565b005b5056fea164736f6c634300060c000a";

type ECDSAExtendedLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ECDSAExtendedLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ECDSAExtendedLib__factory extends ContractFactory {
  constructor(...args: ECDSAExtendedLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ECDSAExtendedLib> {
    return super.deploy(overrides || {}) as Promise<ECDSAExtendedLib>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ECDSAExtendedLib {
    return super.attach(address) as ECDSAExtendedLib;
  }
  connect(signer: Signer): ECDSAExtendedLib__factory {
    return super.connect(signer) as ECDSAExtendedLib__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ECDSAExtendedLibInterface {
    return new utils.Interface(_abi) as ECDSAExtendedLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ECDSAExtendedLib {
    return new Contract(address, _abi, signerOrProvider) as ECDSAExtendedLib;
  }
}
