/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface OwnershipFacetInterface extends utils.Interface {
  functions: {
    "c_6313cdc3(bytes8)": FunctionFragment;
    "c_false6313cdc3(bytes8)": FunctionFragment;
    "c_true6313cdc3(bytes8)": FunctionFragment;
    "owner()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_6313cdc3",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "c_false6313cdc3",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "c_true6313cdc3",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "c_6313cdc3", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "c_false6313cdc3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "c_true6313cdc3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {};
}

export interface OwnershipFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OwnershipFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    c_6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    c_false6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    c_true6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string] & { owner_: string }>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  c_6313cdc3(c__6313cdc3: BytesLike, overrides?: CallOverrides): Promise<void>;

  c_false6313cdc3(
    c__6313cdc3: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  c_true6313cdc3(
    c__6313cdc3: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    _newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    c_6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    c_false6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    c_true6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    c_6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    c_false6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    c_true6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    c_false6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    c_true6313cdc3(
      c__6313cdc3: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
