/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PersonalAccountRegistryInterface extends ethers.utils.Interface {
  functions: {
    "accountImplementation()": FunctionFragment;
    "accountRegistry()": FunctionFragment;
    "addAccountOwner(address,address)": FunctionFragment;
    "addGuardian(address)": FunctionFragment;
    "computeAccountAddress(address)": FunctionFragment;
    "deployAccount(address)": FunctionFragment;
    "executeAccountTransaction(address,address,uint256,bytes)": FunctionFragment;
    "gateway()": FunctionFragment;
    "initialize(address[],address,address)": FunctionFragment;
    "isAccountDeployed(address)": FunctionFragment;
    "isGuardian(address)": FunctionFragment;
    "isInitialized()": FunctionFragment;
    "isValidAccountSignature(address,bytes,bytes)": FunctionFragment;
    "refundAccountCall(address,address,uint256)": FunctionFragment;
    "removeAccountOwner(address,address)": FunctionFragment;
    "removeGuardian(address)": FunctionFragment;
    "upgrade(address)": FunctionFragment;
    "upgradeAccount(address)": FunctionFragment;
    "verifyAccountOwner(address,address)": FunctionFragment;
    "verifyAccountOwnerAtBlock(address,address,uint256)": FunctionFragment;
    "verifyGuardianSignature(bytes32,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accountImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accountRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAccountOwner",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "addGuardian", values: [string]): string;
  encodeFunctionData(
    functionFragment: "computeAccountAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deployAccount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAccountTransaction",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string[], string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isAccountDeployed",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "isGuardian", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidAccountSignature",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundAccountCall",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAccountOwner",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeGuardian",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "upgrade", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeAccount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAccountOwner",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAccountOwnerAtBlock",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyGuardianSignature",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAccountOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeAccountAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeAccountTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAccountDeployed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isGuardian", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidAccountSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundAccountCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAccountOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAccountOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAccountOwnerAtBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyGuardianSignature",
    data: BytesLike
  ): Result;

  events: {
    "AccountCallRefunded(address,address,address,uint256)": EventFragment;
    "AccountDeployed(address,address)": EventFragment;
    "AccountImplementationUpdated(address)": EventFragment;
    "AccountOwnerAdded(address,address)": EventFragment;
    "AccountOwnerRemoved(address,address)": EventFragment;
    "AccountRegistryUpdated(address)": EventFragment;
    "AccountTransactionExecuted(address,address,uint256,bytes,bytes)": EventFragment;
    "AccountUpgraded(address,address)": EventFragment;
    "GuardianAdded(address,address)": EventFragment;
    "GuardianRemoved(address,address)": EventFragment;
    "Initialized(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccountCallRefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountDeployed"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "AccountImplementationUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountOwnerAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountOwnerRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountRegistryUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountTransactionExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GuardianAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GuardianRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export class PersonalAccountRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PersonalAccountRegistryInterface;

  functions: {
    accountImplementation(overrides?: CallOverrides): Promise<[string]>;

    "accountImplementation()"(overrides?: CallOverrides): Promise<[string]>;

    accountRegistry(overrides?: CallOverrides): Promise<[string]>;

    "accountRegistry()"(overrides?: CallOverrides): Promise<[string]>;

    addAccountOwner(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addGuardian(
      guardian: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addGuardian(address)"(
      guardian: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    computeAccountAddress(
      saltOwner: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "computeAccountAddress(address)"(
      saltOwner: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    deployAccount(
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deployAccount(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    executeAccountTransaction(
      account: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeAccountTransaction(address,address,uint256,bytes)"(
      account: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    gateway(overrides?: CallOverrides): Promise<[string]>;

    "gateway()"(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      guardians_: string[],
      accountImplementation_: string,
      gateway_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address[],address,address)"(
      guardians_: string[],
      accountImplementation_: string,
      gateway_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isAccountDeployed(
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isAccountDeployed(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isGuardian(guardian: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isGuardian(address)"(
      guardian: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isInitialized(overrides?: CallOverrides): Promise<[boolean]>;

    "isInitialized()"(overrides?: CallOverrides): Promise<[boolean]>;

    "isValidAccountSignature(address,bytes,bytes)"(
      account: string,
      message: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isValidAccountSignature(address,bytes32,bytes)"(
      account: string,
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    refundAccountCall(
      account: string,
      token: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "refundAccountCall(address,address,uint256)"(
      account: string,
      token: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    removeAccountOwner(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    removeGuardian(
      guardian: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeGuardian(address)"(
      guardian: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    upgrade(
      accountImplementation_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "upgrade(address)"(
      accountImplementation_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    upgradeAccount(
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "upgradeAccount(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    verifyAccountOwner(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "verifyAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verifyAccountOwnerAtBlock(
      account: string,
      owner: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "verifyAccountOwnerAtBlock(address,address,uint256)"(
      account: string,
      owner: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verifyGuardianSignature(
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "verifyGuardianSignature(bytes32,bytes)"(
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  accountImplementation(overrides?: CallOverrides): Promise<string>;

  "accountImplementation()"(overrides?: CallOverrides): Promise<string>;

  accountRegistry(overrides?: CallOverrides): Promise<string>;

  "accountRegistry()"(overrides?: CallOverrides): Promise<string>;

  addAccountOwner(
    account: string,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addAccountOwner(address,address)"(
    account: string,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addGuardian(
    guardian: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addGuardian(address)"(
    guardian: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  computeAccountAddress(
    saltOwner: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "computeAccountAddress(address)"(
    saltOwner: string,
    overrides?: CallOverrides
  ): Promise<string>;

  deployAccount(
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deployAccount(address)"(
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  executeAccountTransaction(
    account: string,
    to: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeAccountTransaction(address,address,uint256,bytes)"(
    account: string,
    to: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  gateway(overrides?: CallOverrides): Promise<string>;

  "gateway()"(overrides?: CallOverrides): Promise<string>;

  initialize(
    guardians_: string[],
    accountImplementation_: string,
    gateway_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address[],address,address)"(
    guardians_: string[],
    accountImplementation_: string,
    gateway_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isAccountDeployed(
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isAccountDeployed(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isGuardian(guardian: string, overrides?: CallOverrides): Promise<boolean>;

  "isGuardian(address)"(
    guardian: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isInitialized(overrides?: CallOverrides): Promise<boolean>;

  "isInitialized()"(overrides?: CallOverrides): Promise<boolean>;

  "isValidAccountSignature(address,bytes,bytes)"(
    account: string,
    message: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isValidAccountSignature(address,bytes32,bytes)"(
    account: string,
    messageHash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  refundAccountCall(
    account: string,
    token: string,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "refundAccountCall(address,address,uint256)"(
    account: string,
    token: string,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  removeAccountOwner(
    account: string,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeAccountOwner(address,address)"(
    account: string,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  removeGuardian(
    guardian: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeGuardian(address)"(
    guardian: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  upgrade(
    accountImplementation_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "upgrade(address)"(
    accountImplementation_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  upgradeAccount(
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "upgradeAccount(address)"(
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  verifyAccountOwner(
    account: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "verifyAccountOwner(address,address)"(
    account: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  verifyAccountOwnerAtBlock(
    account: string,
    owner: string,
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "verifyAccountOwnerAtBlock(address,address,uint256)"(
    account: string,
    owner: string,
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  verifyGuardianSignature(
    messageHash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "verifyGuardianSignature(bytes32,bytes)"(
    messageHash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    accountImplementation(overrides?: CallOverrides): Promise<string>;

    "accountImplementation()"(overrides?: CallOverrides): Promise<string>;

    accountRegistry(overrides?: CallOverrides): Promise<string>;

    "accountRegistry()"(overrides?: CallOverrides): Promise<string>;

    addAccountOwner(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addGuardian(guardian: string, overrides?: CallOverrides): Promise<void>;

    "addGuardian(address)"(
      guardian: string,
      overrides?: CallOverrides
    ): Promise<void>;

    computeAccountAddress(
      saltOwner: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "computeAccountAddress(address)"(
      saltOwner: string,
      overrides?: CallOverrides
    ): Promise<string>;

    deployAccount(account: string, overrides?: CallOverrides): Promise<void>;

    "deployAccount(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    executeAccountTransaction(
      account: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeAccountTransaction(address,address,uint256,bytes)"(
      account: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    gateway(overrides?: CallOverrides): Promise<string>;

    "gateway()"(overrides?: CallOverrides): Promise<string>;

    initialize(
      guardians_: string[],
      accountImplementation_: string,
      gateway_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address[],address,address)"(
      guardians_: string[],
      accountImplementation_: string,
      gateway_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isAccountDeployed(
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isAccountDeployed(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isGuardian(guardian: string, overrides?: CallOverrides): Promise<boolean>;

    "isGuardian(address)"(
      guardian: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isInitialized(overrides?: CallOverrides): Promise<boolean>;

    "isInitialized()"(overrides?: CallOverrides): Promise<boolean>;

    "isValidAccountSignature(address,bytes,bytes)"(
      account: string,
      message: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isValidAccountSignature(address,bytes32,bytes)"(
      account: string,
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    refundAccountCall(
      account: string,
      token: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "refundAccountCall(address,address,uint256)"(
      account: string,
      token: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    removeAccountOwner(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    removeGuardian(guardian: string, overrides?: CallOverrides): Promise<void>;

    "removeGuardian(address)"(
      guardian: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgrade(
      accountImplementation_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgrade(address)"(
      accountImplementation_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeAccount(account: string, overrides?: CallOverrides): Promise<void>;

    "upgradeAccount(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    verifyAccountOwner(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "verifyAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifyAccountOwnerAtBlock(
      account: string,
      owner: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "verifyAccountOwnerAtBlock(address,address,uint256)"(
      account: string,
      owner: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifyGuardianSignature(
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "verifyGuardianSignature(bytes32,bytes)"(
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    AccountCallRefunded(
      account: null,
      beneficiary: null,
      token: null,
      value: null
    ): EventFilter;

    AccountDeployed(account: null, accountImplementation: null): EventFilter;

    AccountImplementationUpdated(accountImplementation: null): EventFilter;

    AccountOwnerAdded(account: null, owner: null): EventFilter;

    AccountOwnerRemoved(account: null, owner: null): EventFilter;

    AccountRegistryUpdated(accountRegistry: null): EventFilter;

    AccountTransactionExecuted(
      account: null,
      to: null,
      value: null,
      data: null,
      response: null
    ): EventFilter;

    AccountUpgraded(account: null, accountImplementation: null): EventFilter;

    GuardianAdded(sender: null, guardian: null): EventFilter;

    GuardianRemoved(sender: null, guardian: null): EventFilter;

    Initialized(initializer: null): EventFilter;
  };

  estimateGas: {
    accountImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    "accountImplementation()"(overrides?: CallOverrides): Promise<BigNumber>;

    accountRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    "accountRegistry()"(overrides?: CallOverrides): Promise<BigNumber>;

    addAccountOwner(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addGuardian(guardian: string, overrides?: Overrides): Promise<BigNumber>;

    "addGuardian(address)"(
      guardian: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    computeAccountAddress(
      saltOwner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "computeAccountAddress(address)"(
      saltOwner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deployAccount(account: string, overrides?: Overrides): Promise<BigNumber>;

    "deployAccount(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    executeAccountTransaction(
      account: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeAccountTransaction(address,address,uint256,bytes)"(
      account: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    gateway(overrides?: CallOverrides): Promise<BigNumber>;

    "gateway()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      guardians_: string[],
      accountImplementation_: string,
      gateway_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address[],address,address)"(
      guardians_: string[],
      accountImplementation_: string,
      gateway_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isAccountDeployed(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isAccountDeployed(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isGuardian(guardian: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isGuardian(address)"(
      guardian: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isInitialized(overrides?: CallOverrides): Promise<BigNumber>;

    "isInitialized()"(overrides?: CallOverrides): Promise<BigNumber>;

    "isValidAccountSignature(address,bytes,bytes)"(
      account: string,
      message: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isValidAccountSignature(address,bytes32,bytes)"(
      account: string,
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    refundAccountCall(
      account: string,
      token: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "refundAccountCall(address,address,uint256)"(
      account: string,
      token: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    removeAccountOwner(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    removeGuardian(guardian: string, overrides?: Overrides): Promise<BigNumber>;

    "removeGuardian(address)"(
      guardian: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    upgrade(
      accountImplementation_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "upgrade(address)"(
      accountImplementation_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    upgradeAccount(account: string, overrides?: Overrides): Promise<BigNumber>;

    "upgradeAccount(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    verifyAccountOwner(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "verifyAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyAccountOwnerAtBlock(
      account: string,
      owner: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "verifyAccountOwnerAtBlock(address,address,uint256)"(
      account: string,
      owner: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyGuardianSignature(
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "verifyGuardianSignature(bytes32,bytes)"(
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accountImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "accountImplementation()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    accountRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "accountRegistry()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addAccountOwner(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addGuardian(
      guardian: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addGuardian(address)"(
      guardian: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    computeAccountAddress(
      saltOwner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "computeAccountAddress(address)"(
      saltOwner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployAccount(
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deployAccount(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    executeAccountTransaction(
      account: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeAccountTransaction(address,address,uint256,bytes)"(
      account: string,
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    gateway(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "gateway()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      guardians_: string[],
      accountImplementation_: string,
      gateway_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address[],address,address)"(
      guardians_: string[],
      accountImplementation_: string,
      gateway_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isAccountDeployed(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isAccountDeployed(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isGuardian(
      guardian: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isGuardian(address)"(
      guardian: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isInitialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isInitialized()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isValidAccountSignature(address,bytes,bytes)"(
      account: string,
      message: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isValidAccountSignature(address,bytes32,bytes)"(
      account: string,
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    refundAccountCall(
      account: string,
      token: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "refundAccountCall(address,address,uint256)"(
      account: string,
      token: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    removeAccountOwner(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    removeGuardian(
      guardian: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeGuardian(address)"(
      guardian: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    upgrade(
      accountImplementation_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "upgrade(address)"(
      accountImplementation_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    upgradeAccount(
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "upgradeAccount(address)"(
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    verifyAccountOwner(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verifyAccountOwner(address,address)"(
      account: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyAccountOwnerAtBlock(
      account: string,
      owner: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verifyAccountOwnerAtBlock(address,address,uint256)"(
      account: string,
      owner: string,
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyGuardianSignature(
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verifyGuardianSignature(bytes32,bytes)"(
      messageHash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
